name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: HeroTest.testConstructor1
      id: herotest-testconstructor1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HeroTest.testConstructor1
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testConstructor1"
        timeout: 10
        max-score: 4
    - name: HeroTest.testConstructor2
      id: herotest-testconstructor2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HeroTest.testConstructor2
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testConstructor2"
        timeout: 10
        max-score: 4
    - name: HeroTest.testConstructor3
      id: herotest-testconstructor3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HeroTest.testConstructor3
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testConstructor3"
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HEROTEST-TESTCONSTRUCTOR1_RESULTS: "${{steps.herotest-testconstructor1.outputs.result}}"
        HEROTEST-TESTCONSTRUCTOR2_RESULTS: "${{steps.herotest-testconstructor2.outputs.result}}"
        HEROTEST-TESTCONSTRUCTOR3_RESULTS: "${{steps.herotest-testconstructor3.outputs.result}}"
      with:
        runners: herotest-testconstructor1,herotest-testconstructor2,herotest-testconstructor3
